version: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5435:5432"
    networks:
      - restkeeper
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/
  minio:
    env_file: .env
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data/
    networks:
      - restkeeper
    volumes:
      - minio-data:/data
  backend:
    build: .
    container_name: restkeeper-backend
    ports:
      - "8080:8080"
    networks:
      - restkeeper
    depends_on:
      - postgres
      - minio
    env_file:
      - ./.env
  frontend:
    image: hizmailovich/restkeeper-frontend
    container_name: restkeeper-frontend
    ports:
      - "4200:4200"
    networks:
      - restkeeper

volumes:
  minio-data:
    driver: local
  pgdata:
    driver: local

networks:
  restkeeper:
    driver: bridge