server:
  port: 8080
  shutdown: graceful

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  minio:
    bucket: ${MINIO_BUCKET}
    access-key: ${MINIO_USER}
    secret-key: ${MINIO_PASSWORD}
    url: ${MINIO_URL}
#  jackson:
#    default-property-inclusion: NON_NULL

restkeeper:
#  context-path: /restkeeper/v1
  security:
    access-key: ${RESTKEEPER_SECRETS_ACCESS-KEY}
    refresh-key: ${RESTKEEPER_SECRETS_REFRESH-KEY}
    enable-key: ${RESTKEEPER_SECRETS_ENABLE-KEY}
    password-refresh-key: ${RESTKEEPER_SECRETS_PASSWORD-REFRESH-KEY}
    access-expiration-time: ${RESTKEEPER_SECRETS_ACCESS-EXPIRATION-TIME}
    refresh-expiration-time: ${RESTKEEPER_SECRETS_REFRESH-EXPIRATION-TIME}
mail:
  host: ${MAIL_HOST}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  port: ${MAIL_PORT}
  protocol: ${MAIL_PROTOCOL}
